name: 'shopstream_dbt'
version: '1.0.0'
config-version: 2

profile: 'shopstream'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  shopstream_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
